### ISSUE TITLE
The tool doesn't scan all css files

### ISSUE THREAD

**Issue by martirosyan-kar** [YellowLabTools/YellowLabTools#261] opened 2018-02-26 19:55 UTC
http://yellowlab.tools/result/eyhqrnq1bp

The rules count is shown 1348, and if you open it `http://yellowlab.tools/result/eyhqrnq1bp/rule/cssRules`, you will see 3 files. 

If we open the website
https://www.mdsave.com/procedures/mri-with-and-without-contrast/d781f5cb?clickSource=carousel

There is also `https://assets.mdsave.com/app/styles/main.{something}.css ` which is missing in the report above. 

What could be the reason? 

Thank you.

**Comment by gmetais** [comment] 2018-02-28 01:06
Hi!

I've had a look and it looks like the CSS analysis of main.xxx.css starts and never ends. I have no clue for the moment and I will try to investigate a bit more when I have time. Thanks for filling this issue!

**Comment by gmetais** [comment] 2018-03-02 20:25
Still no clue... It looks like an [analyze-css](https://github.com/macbre/analyze-css) gets lost. Or maybe the page analysis ends before this process. It's kind of hard to debug because I don't reproduce on my machine.

**Comment by martirosyan-kar** [comment] 2018-03-05 20:19
Hi @gmetais. Thanks for looking into this. 
Just making sure, by saying `I don't reproduce on my machine` you mean when you run locally, it works? 

Also, it was working on December 17 we ran the scan. The bug appeared after that for sure. Maybe a package? 

Thank You.

**Comment by gmetais** [comment] 2018-03-05 20:40
Yes I mean it's working locally, on my development environment.

There were no changes and no deploy between December 17 and March, so I guess it's something tricky like the order of execution of the CSS tests...

**Comment by gmetais** [comment] 2021-02-03 23:33
This is supposed to be fixed by #327.

**Closed by gmetais** 2021-02-03 23:33 UTC
Labels: bug
