### ISSUE TITLE
Development version feedback

### ISSUE THREAD

**Issue by uhlhosting** [YellowLabTools/YellowLabTools#325] opened 2021-01-25 17:31 UTC
First I think this is amazing and I see improvements, I used the latest docker image I found:

Here are my findings:
- versioning is missing:
<img width="362" alt="image" src="https://user-images.githubusercontent.com/6324047/105741676-e33b7a80-5f3a-11eb-8aea-bbee65ad57bb.png">
- when pulling and running the docker deployment:

```
Status: Downloaded newer image for ousamabenyounes/yellowlabtools:latest
(node:1) V8: /usr/src/ylt/node_modules/ttf2woff2/jssrc/ttf2woff2.js:3 Invalid asm.js: Invalid member of stdlib
(Use `node --trace-warnings ...` to show where the warning was created)
Listening on port 8383
```

- the tablet is displayed lower in the view, until now tested on @Safari only.
<img width="533" alt="image" src="https://user-images.githubusercontent.com/6324047/105741848-11b95580-5f3b-11eb-9ad9-b00e5f30a181.png">
- when using "/" at the end of the address there will occur an error:

```
----
Test failed
Phantomas failed: net::ERR_CERT_DATE_INVALID at https://uhl.site/
----
Launching test fv9gv3waxy on https://uhl.site
Launching test fv9gvp9n7e on https://uhl.site/
Error: net::ERR_CERT_DATE_INVALID at https://uhl.site/
    at navigate (/usr/src/ylt/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:115:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async FrameManager.navigateFrame (/usr/src/ylt/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:90:21)
    at async Frame.goto (/usr/src/ylt/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:417:16)
    at async Page.goto (/usr/src/ylt/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:784:16)
    at async /usr/src/ylt/node_modules/phantomas/lib/browser.js:273:7
Test failed for URL: https://uhl.site/
```

These are my findings at first deployment, I have it running maybe 10 mins :)
Keep up the good work!

**Comment by gmetais** [comment] 2021-01-31 02:07
Hi @uhlhosting,

Thanks a lot for your precious feedback!

I have fixed version number not showing on private instances.

And I think the Safari bug is also fixed now (though I couldn't reproduce it on my Safari).

I don't have much clues about the `/usr/src/ylt/node_modules/ttf2woff2/jssrc/ttf2woff2.js:3` error. I've read that it was only appearing on node > 12. But does it really break font conversion? Could you please test on a website that is missing WOFF2 compression (such as https://www.operadeparis.fr/) and tell me whether the "WOFF 2" rule is green or red?

I really have no clue about the `ERR_CERT_DATE_INVALID` bug you have. I can't reproduce on the URL you mention.

**Comment by uhlhosting** [comment] 2021-01-31 11:17
Hi @gmetais here are the results, the ERR CERT is not always repeating, randomly from time to time.

https://speed.uhl.site/result/fvfeo84ocy

**Comment by gmetais** [comment] 2021-01-31 12:24
Thanks! It looks like the ttf2woff2 library is working correctly, you can ignore the warning.

Regarding the certificate error, I've tested several times on two different machines and I still can't reproduce. Could the server where you host YLT have a wrong date/time?

**Comment by uhlhosting** [comment] 2021-01-31 17:56
Its having the right time.

**Comment by uhlhosting** [comment] 2021-02-10 14:44
Some more errors from docker side:

```
Phantomas failed: net::ERR_CERT_DATE_INVALID at https://uhl.site
Launching test fvmncmkvp9 on https://uhl.site/
Error: net::ERR_CERT_DATE_INVALID at https://uhl.site/
    at navigate (/usr/src/ylt/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:115:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async FrameManager.navigateFrame (/usr/src/ylt/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:90:21)
    at async Frame.goto (/usr/src/ylt/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:417:16)
    at async Page.goto (/usr/src/ylt/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:784:16)
    at async /usr/src/ylt/node_modules/phantomas/lib/browser.js:273:7
Test failed for URL: https://uhl.site/
Phantomas failed: net::ERR_CERT_DATE_INVALID at https://uhl.site/
Launching test fvmncrz1ob on https://uhl.site
Error: net::ERR_CERT_DATE_INVALID at https://uhl.site
    at navigate (/usr/src/ylt/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:115:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async FrameManager.navigateFrame (/usr/src/ylt/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:90:21)
    at async Frame.goto (/usr/src/ylt/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:417:16)
    at async Page.goto (/usr/src/ylt/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:784:16)
    at async /usr/src/ylt/node_modules/phantomas/lib/browser.js:273:7
Test failed for URL: https://uhl.site
Phantomas failed: net::ERR_CERT_DATE_INVALID at https://uhl.site
Launching test fvmnd3wisj on https://uhl.site
Launching test fvp6hf6l03 on https://visolab.group/
Launching test fvp6o12802 on https://visolab.group/
Launching test fvp6qb9ecf on https://visolab.group/
Launching test fvp6sqs1qq on https://visolab.group/
```

**Comment by uhlhosting** [comment] 2021-02-10 14:45
I am very curious to know how about the visolab.group got into my docker logs, i have nothing to do with that domain... Anyone any idea? This is a bit weird.

**Comment by gmetais** [comment] 2021-02-10 20:16
Hmmm... that's not me. Could it be someone who clicked on the URL you provided above and decided to use it? Edit your comment to prevent re-use.

I'll take a look this weekend at Chromiums flags that could maybe avoid this certificate error!

**Comment by uhlhosting** [comment] 2021-02-11 00:37
@gmetais i dont mind people using it, just here to try to learn more and fix solve issues i found.

**Comment by gmetais** [comment] 2021-02-20 13:10
Ok, I'm pretty sure I've fixed the CERT error. If you have some time, update to the lastest version of the develop branch and restart your server. 

Thanks a lot for spotting it! I'm closing the issue, feel free to re-open :)

**Closed by gmetais** 2021-02-20 13:10 UTC

**Comment by uhlhosting** [comment] 2021-02-21 00:56
@gmetais would be also great if you update the docs @ the usage for new people, its hard to find the correct docker configs, since there are more. Also some basic changes would help.

**Comment by ousamabenyounes** [comment] 2021-02-26 19:30
thanks a lot @uhlhosting  for your precious feedback 
I just updated the docker image and now last version of YLT is available and lot of other last fixes from @gmetais  

`docker run --privileged -p 8383:8383    ousamabenyounes/yellowlabtools `

I will try to update this image everytime new fixes are pushed to stay connected with latest V2 version

Thank you again

**Comment by uhlhosting** [comment] 2021-02-26 22:34
@gmetais we are on latest dev branch, and still no fixes are visible, either the @ @ version, nor the SSL shows as fixed. Maybe the push did not succeeded?

**Comment by gmetais** [comment] 2021-02-26 22:47
I tried a hour ago and it was working fine (didn't try the SSL though).

I had to completely delete the image and reinstall it from scratch. And I also had to hard refresh the page in my browser to remove the @ @ version.

**Comment by uhlhosting** [comment] 2021-02-26 23:50
In that case not sure where is the issue. You can always check my deployment is on same address.

**Comment by ousamabenyounes** [comment] 2021-02-27 01:46
I recommend you to ru' a docker rm of your actual image and then launch a docjer run
You ll see it will pull the new version.
It seems that your actual container use the previous image from local cache instead if pulling new versions
