### ISSUE TITLE
link prefetch appears to show-up as double image download on "page weight"

### ISSUE THREAD

**Issue by a701440** [YellowLabTools/YellowLabTools#227] opened 2017-04-05 19:44 UTC
We have link rel="prefetch" href="..." in the head for a large image that is also used lower on the page. On the page weight report it appears that the image is counted two times and lowers the score.

**Comment by gmetais** [comment] 2017-04-05 21:17
Hi,

I'm a bit surprised. Could you please check if the request's caching headers are correct? No "no-cache" and a "max-age" > 0 ?

And share the page url if it's not private!

**Comment by a701440** [comment] 2017-04-05 21:29
https://www.kayak.com/hotels 
with cookie features=horizonleancomp

**Comment by gmetais** [comment] 2017-04-05 22:05
Thanks for the url.
It looks like PhantomJS records two different requests and this is a bug. I'll have a look into this when I have a bit more time!

**Comment by gmetais** [comment] 2017-05-27 16:34
Hi @a701440,

It looks like your `prefetch` link got recently replaced by `preload`. Preload is more relevant in your use case, but it's not supporter by the version of PhantomJS (v2.1) in use in YLT.

I keep this bug about `prefetch` open and I'll try to reproduce it on test webpage.

**Comment by gmetais** [comment] 2018-03-02 20:42
Tested (finally) on a very simple page:

```html
<html>
<head>
    <title>Page with a prefetched image</title>
    <link rel="prefetch" href="png-image.png">
</head>
<body>
    <img src="png-image.png">
</body>
</html>
```

Phantomas detects two different images. Let's wait for the next version that should run on Chrome's headless mode.

**Comment by gmetais** [comment] 2021-02-03 23:30
Fixed by #327.

**Closed by gmetais** 2021-02-03 23:30 UTC
Labels: bug
